default: &default
  adapter: postgresql
  encoding: unicode
  host: ruby-skeleton-db
  username: postgres
  password: password
  pool: 5
  port: 5432

development:
  <<: *default
  database: myapp_development

test:
  <<: *default
  database: myapp_test